# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Service File Modified
        id: changed
        run: |
          changed=false
          for cf in ${{ steps.files.outputs.all }}; do
            if [[ $cf == *.service ]]; then changed=true; fi
          done
          echo $changed
          echo "::set-output name=changed::$changed"
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: "http://ec2-3-11-98-113.eu-west-2.compute.amazonaws.com:9000/deploy"
          method: "POST"
          data: '{"repo": "${{ inputs.repo }}", "service_file_changed": ${{ steps.changed.outputs.changed }}}'
